### ISSUE TITLE
email address?

### ISSUE THREAD

**Issue by abhijitsam** [netneutrality/savetheinternet.in#11]
err.. have i missed anything.. so sorry to ask.. but the email should be sent to which address? also any particular "Subject"?

**Comment by maxweldsouza** [comment]
advqos@trai.gov.in

**Comment by aravindet** [comment]
This should have been pre-filled when you clicked on Send email (on phone) or your email provider's button (Gmail, Yahoo or other - on desktop). Did this not happen for you?

Please give more information so that we can try to fix. Such as: What device and browser do you use? What email provider? What are the steps you took, and what happened?

**Comment by gagan97** [comment]
I'm xiaomi note with Google inbox and its not pre-filled

**Comment by abhijitsam** [comment]
@aravindet  : no that did not happen.. it just got copied in my clipboard.
Specs : 
Desktop - Chrome - Yahoo
I clicked on yahoo.. it just redirected me to yahoo mail..I had to explicitly click on compose mail.

**Comment by ishansharma** [comment]
Google Inbox will be fixed in latest release (to be out soon).
