### ISSUE TITLE
Windows Phone IE send button doesn't work 

### ISSUE THREAD

**Issue by asdofindia** [netneutrality/savetheinternet.in#56]
The send button can be pressed and shows the dotted border. But this doesn't cause any action.

Reported on a range of lumia phones.

**Comment by miteshashar** [comment]
You mean the modal doesn't show up? @asdofindia

**Comment by asdofindia** [comment]
Yeah. No modal. 
It feels just like preventDefault on a hyperlink.

**Comment by sakshamsaxena** [comment]
Not working on UC on WP as well. Will be looking into it shortly.

**Comment by sakshamsaxena** [comment]
Emulated the website through desktop's IE.
![1](https://cloud.githubusercontent.com/assets/8774516/7105779/5b70ce74-e147-11e4-91a1-52b66a10a263.PNG)
![2](https://cloud.githubusercontent.com/assets/8774516/7105780/5b7d25ac-e147-11e4-852a-578a2edd4ca3.PNG)
The error (SCRIPT 122) is related to IE not able to handle the length of URI for some reason. Makes sense though. 
Tried a couple of things and found out that the loops and conditions are met as desired. This clearly points that the long URI is the problem here for IE.

**Comment by miteshashar** [comment]
@asdofindia @sakshamsaxena Does the latest version of the site face these issues?

**Comment by aravindet** [comment]
Let us switch to copy-paste flow for IEMobile. Remove it from the isMobile
regex.

**Comment by sakshamsaxena** [comment]
@miteshashar I can edit answers just fine now, but yeah the Send option isn't working still. Same error in console which I quoted above. Need to write an altogether different approach to handle IE on WP.

**Comment by miteshashar** [comment]
Can you please test on http://stage-savetheinternet.herokuapp.com and give me some feedback?

1. Can people with IE on Windows Phones & desktop test whether (a) popup opens (b) ur able to copy the text (c) after ur done copying, there is just one button to mail, and your mail client does open.
2. Can NON WINDOWS & NON-IE folks please give me feedback on whether it works on whatever platform you're testing on. A short affirmative with your platform will help us ensure that the main site doesn't stop working for others.

**Comment by asdofindia** [comment]
Android - Firefox: works 
Linux - Firefox: works
iOS - Safari: works

**Comment by menatankush** [comment]
Works on:
Android : Chrome with Google Inbox, Gmail
Linux : Chrome, Firefox with Geary

Doesn't work on.
Android: Chrome with "stock Email app"

**Comment by miteshashar** [comment]
OK. @asdofindia & @menatankush  thanks for the feedback.
