### ISSUE TITLE
Error while running grunt command 

### ISSUE THREAD

**Issue by ermauliks** [netneutrality/savetheinternet.in#64]
I'm not sure its only me or anyone else too getting this error

![image](https://cloud.githubusercontent.com/assets/3040988/7105358/fd263396-e131-11e4-936e-018a1d489bd9.png)

**Comment by miteshashar** [comment]
@ermauliks We stopped using the `dist` folder and grunt.

**Comment by sarbbottam** [comment]
I faced the same. It is due to the referencing css file with respect to the root [`/css/bootstrap.css?v1`](https://github.com/netneutrality/savetheinternet.in/blob/stage/src/index.html#L11)
On replacing `/css/bootstrap.css?v1` with `css/bootstrap.css?v1`, the error get resolved.
However, there are client side JS issue, with the compiled JS.

>> We stopped using the dist folder and grunt.

My 0.02 :dollar:, I guess there are chances of refactoring the code base (mainly html), and use template to keep it minimal, and generating the desired files from the templates.
