### ISSUE TITLE
[Feature Request] Add https support

### ISSUE THREAD

**Issue by jatindhankhar** [netneutrality/savetheinternet.in#77]
Add the https support, to move the web forward.

Quoting from the [blog of Hasgeek]() 
<blockquote>
HTTP has always been an insecure protocol – your communications are sent back and forth in plain text, readable by anyone tapping your internet connection – but the cost of switching to HTTPS and general public apathy has left us with most sites still on HTTP. </blockquote>

Free plans can be added from [CloudFlare](http://cloudflare.com/)

A suggestion : Github Pages can be effectively used for serving pages without any compromise, backed with Cloudflare, site will never go down

**Comment by jace** [comment]
Since you aren't submitting anything to the site, HTTPS doesn't change anything. It only prevents anyone from knowing you visited the site. However in this case you want to announce that you went to the site and sent an email.

We debated whether the site needed HTTPS and realised (a) it wasn't necessary and (b) we could spend our time better adding more features and fixing edge cases.

**Comment by jatindhankhar** [comment]
Yes, your arguments make more sense. 
Closing the issue
But consider Github Pages, may help in cutting down hosting costs :smile:

**Comment by jace** [comment]
We're on Heroku's free plan and it's holding up well.

**Comment by aravindet** [comment]
I'll look at doing this anyway, but not a high priority.

1. Prevents telcos from tampering with the page tricking people into
sending the wrong thing. (Far fetched but you never know).

2. Encrypting everything serves a social good as it increases the cost of
bulk surveillance. We will make a good impact here because heroku shares
IPs and we have massive traffic. (Also not a critical issue as far as our
campaign is concerned)
