### ISSUE TITLE
proposal/suggestion

### ISSUE THREAD

**Issue by sarbbottam** [netneutrality/savetheinternet.in#88]
Proposal/Suggestion 
---
* refactor to keep the code modular and use template
* keep the following separate 
  * templates
  * data
  * copy
  * css
  * javascript
* generate the desired composite from the modular 
  * templates
  * data
  * copy
  * css
  * javascript
* use a template engine to create the composite
* use a task runner (preferably grunt, gulp) to achieve the above
* test cases
  * unit
  * functional [sauce labs](https://saucelabs.com/) could be utilized.

What would we gain out of it?
---
Separation of concerns and thus maintainability.

**Comment by c-das** [comment]
+1 this could also make translations easier to integrate/manage [https://github.com/netneutrality/savetheinternet.in/issues/52]

**Comment by karthikb351** [comment]
+1 as well

Initially things were too unstable, and a system like would just slow us down. But we translations coming in, it makes sense to mode to a template system.

None of us have the bandwidth currently to do this at the moment, maybe over the next couple of days.

cc: @miteshashar

**Comment by miteshashar** [comment]
@sarbbottam Yes. We are all for it.
The only thing that has been stopping us is bandwidth, like @karthikb351 said.
Feel free to submit PRs if you can manage.
You have pretty much covered everything. Just appending to it below:
1. The priority is modularisation as it will enable a lot of stuff, including translation like @c-das said.
2. A test suite would never hurt. It can make life easy, specially with the whole functional workflow. But it is still something we can manage getting through without, because this is a short-term project.

**Comment by sarbbottam** [comment]
:maple_leaf: Lets keep this thread open for any followup discussion.

---
I would get started on the first cut of the modular code base.

Could you please help me understand the followings:
* Why there are two sets of answer to every question but only one is visible to the users?
* How many answers can there be for each question?
* If there are multiple answer, what is the deciding factor to choose the answer?

---

Is there any documentation on the probable sequence of interaction/flow? If not do you prefer to initiate the same? I believe it will be faster or any new participant to contribute more. Going through the code, to comprehend the desired interaction, might require more time.

**Comment by crc442** [comment]
The site needs a redesign. If it's worth it, I can mock some designs here and make a PR.

**Comment by jace** [comment]
Sure, but keep in mind that it has an average of 2000-3000 users on the site at any given time during the day, with daily pageviews of 500,000. That's far more traffic than most sites get. We are also catering to:

1. Majority mobile audience (> 60%),
2. Who are on slow EDGE or GPRS connections, and
3. Who need to see an unambiguous call to action regarding emailing TRAI.

To achieve this:

1. The site needs to be as lean as possible, preferably without jQuery and other such large dependencies,
2. No external dependencies like fonts and images (except the logo), and
3. Everything inlined so that there is no scope for some resource failing to load.

Given these constraints, go ahead with a redesign. The campaign has another week to run.

**Comment by jace** [comment]
@sarbbottam answers are selected at random from the available set. We had an earlier mockup where users could browse through the options, but it didn't make it to production.

**Comment by sarbbottam** [comment]
>> answers are selected at random from the available set.

Thanks @jace. 

Is there a finite set of answers (so far I have seen only two), this information will help to structure the data.

**Comment by shrayasr** [comment]
> Is there a finite set of answers (so far I have seen only two), this information will help to structure the data.

There are no such constraint AFAIK. As more answers are written, they can be added in.

**Comment by miteshashar** [comment]
True. No limit on number of answer options.

**Comment by crc442** [comment]
@jace Thanks. That sounds good. I'll see what I can do :+1:
